### ISSUE TITLE
Get Help section

### ISSUE THREAD

**Issue by aabhaskharel** [arncv/Intima#102]
Are there any plans to add a new section like maybe a 'Get Help' section? 

Which can have information about different organizations and government initiatives that offer sexual health services and resources.

Their website link, address, contact info, and such.

**Comment by suchhanda** [comment]
Hey, I would like to work on this. Can you please assign this to me?

**Comment by arncv** [comment]
Assigned!

**Comment by khamkarsuraj** [comment]
Hello @arncv,
Can I work on this issue if no one is working?

**Comment by arncv** [comment]
@khamkarsuraj Go ahead, All yours!

**Comment by khamkarsuraj** [comment]
Hello @arncv, I would like to work on another issue I found for Intima. Please, unassign me as of now.

**Comment by patilanuja** [comment]
@arncv could you please assign this to me, I would like to work on this issue.

**Comment by arncv** [comment]
@khamkarsuraj No worries!
@patilanuja Assigned! All yours.

**Comment by patilanuja** [comment]
@arncv  Could you please take a look at my PR.
