### ISSUE TITLE
Proposal: Add a 'Back' button for the quiz

### ISSUE THREAD

**Issue by Emilio-PdeA** [arncv/Intima#108]
**What Issue**
The quiz goes only one way. It would be good to add a 'back' button to go to the previous question. What do you think?

**Proposed Changes**
Add back button with quiz history of previous questions.

**Any other info**
I could also make the 'next' button to change to 'submit' button for the last question

**Comment by Emilio-PdeA** [comment]
Could I get assigned to it?

**Comment by arncv** [comment]
@Emilio-PdeA Assigned!
