### ISSUE TITLE
Improve Chat Page

### ISSUE THREAD

**Issue by arncv** [arncv/Intima#11]
Intima bot page right now kind of stands out from the rest of the website. It's not really following the default theme, you know? 
It would be awesome if we could streamline it and make it blend in smoothly with the rest. Also, gotta admit, the chat page could use some more polishing too.

**Comment by Saraswata-18** [comment]
By theme You mean only the styling part?

**Comment by arncv** [comment]
@Saraswata-18 Yes, the bot page appears to be a separate page of its own, It should blend in well with the rest of the website (adding a nav bar, back button, etc.)

**Comment by Saraswata-18** [comment]
Ok please assign this to me !!

**Comment by arncv** [comment]
Assigned!

**Comment by Saraswata-18** [comment]
Made a Pull Request

**Comment by TusharGagal** [comment]
I will improve the styling of a Chat page.
currently it looking like this:
![image](https://github.com/arncv/Intima/assets/110715565/57e25582-e184-4965-84cb-d4c82cbf74c2)
i will make it more better by adding css.
please assign it to me.

**Comment by arncv** [comment]
Assigned!

**Comment by TusharGagal** [comment]
Thank you

**Comment by TusharGagal** [comment]
#92 raised a pr please check it and merge it.

**Comment by arncv** [comment]
Merged!
