### ISSUE TITLE
Navbar items not aligned properly

### ISSUE THREAD

**Issue by Joshlansah1** [arncv/Intima#116]
What Issue - The items in the navbar have not been aligned properly.

Proposed Changes - Align navbar items to add a consistent feel to the navbar.

@arncv Please assign me to this issue and I will fix it

Please assign me the necessary labels

**Comment by arncv** [comment]
@Joshlansah1 Assigned!

**Comment by Joshlansah1** [comment]
Thank you. I am done. I have submitted a pull request

**Comment by arncv** [comment]
@Joshlansah1 Thank you for fixing this. Closing issue
