### ISSUE TITLE
dark mode toggle image looking weird on smaller devices

### ISSUE THREAD

**Issue by Joshlansah1** [arncv/Intima#117]
What Issue - The dark mode toggle image looks stretched on smaller devices

Proposed Changes - Adjust the image to look better on smaller devices

@arncv Please assign me to this issue to get it fixed

**Comment by Joshlansah1** [comment]
Everything works well

**Comment by arncv** [comment]
@Joshlansah1 Wonderful work! Thank you for fixing this bug
