### ISSUE TITLE
BUG - Dark Mode Inverts the Colors of Page 

### ISSUE THREAD

**Issue by arncv** [arncv/Intima#14]
- When dark mode is enabled, the colors of icons and photos on the website are inverted.
- The navigation bar remains in light mode even when dark mode is turned on.

**Comment by SurajPrakash24** [comment]
Can you please assign this issue to me

**Comment by arncv** [comment]
Apologies, this bug was fixed in the latest PR, you can see more issues at https://github.com/arncv/Intima/issues/.
Happy Hacktoberfest!
