### ISSUE TITLE
Improve Resources Section

### ISSUE THREAD

**Issue by arncv** [arncv/Intima#16]
- Edit / Proofread the resources for any possible misspelling/error
- Add link with each topic so that the user can learn more about the topic.
- (Curate a list of external resources, books, or courses that beginners can refer to for deeper understanding.)

**Comment by sarafurd** [comment]
please assign to me

**Comment by arncv** [comment]
Assigned!

**Comment by sarafurd** [comment]
Where should I put the link for the topic?

**Comment by arncv** [comment]
Links should be displayed on the informational pop-up page when the 'Learn More' button is clicked.

**Comment by sarafurd** [comment]
So like this?
![image](https://github.com/arncv/Intima/assets/67877801/372c1c92-77ac-4504-ac3a-413b810e5649)

**Comment by arncv** [comment]
Yeah that looks good! 
Make sure that the external links are of reliable sources(like cdc, nhs or other medical websites)

**Comment by sarafurd** [comment]
okay sounds good

**Comment by Rajiv-paul** [comment]
can I get assigned for this issue please

**Comment by arncv** [comment]
@Rajiv-paul This issue has been marked closed as it was fixed in the latest pr.
