### ISSUE TITLE
the footer and the header are not styled correctly

### ISSUE THREAD

**Issue by ShakthiW** [arncv/Intima#25]
the header is not taking the full width of the page and footer text cant be seen as the background of that div is the same color as the tecxt

**Comment by Gurnav224** [comment]
I would like to work on the issue assign it to me

**Comment by Stormbreakerr20** [comment]
Can you assign this to me.....

**Comment by arncv** [comment]
Thank you for pointing out this issue.

I've assigned both of you @ShakthiW & @Stormbreakerr20 the issue. 
Happy Hacktoberfest!

**Comment by Stormbreakerr20** [comment]
I have Raised a PR solving this issue
