### ISSUE TITLE
Update Contributors section in Readme

### ISSUE THREAD

**Issue by arncv** [arncv/Intima#29]
**Current State:**
The Contributors section of readme currently does not update with new contributors.
![image](https://github.com/arncv/Intima/assets/62099328/ec6663fc-6c6c-4203-a1dc-080e346aca02)

**Proposed Changes:**
Generate new contributor's link and update it in the readme.

Link to generate : https://contrib.rocks/preview?repo=arncv%2Fintima

**Comment by jfmartinz** [comment]
can you please assign this issue to me?

**Comment by arncv** [comment]
Assigned!
