### ISSUE TITLE
Interactive Quiz Section

### ISSUE THREAD

**Issue by arncv** [arncv/Intima#32]
Create an interactive quiz section where users can test their knowledge about sexual health. This could be a fun and engaging way to learn.

**Comment by TusharGagal** [comment]
Can you assign me this?

**Comment by TusharGagal** [comment]
![image](https://github.com/arncv/Intima/assets/110715565/18e88c73-092f-47c1-9d23-242006e3af75)

can i add a button here for a quiz so that if user hit that button than a new page will open for a quiz??

**Comment by arncv** [comment]
Adding a button right beside the Get Started would look better in my opinion! Opening the quiz in new page would also be good option as the main page would be less cluttered.

**Comment by TusharGagal** [comment]
yeah i also thought that this would be the better option

**Comment by arncv** [comment]
Thank you! ❤️
