### ISSUE TITLE
Add Copy Link Buttons:

### ISSUE THREAD

**Issue by arncv** [arncv/Intima#34]
For each term in the resources tab, Add a copy link button inside the pop up page that appears after clicking the learn more button.

- The link should redirect to the pop up when opened

**Comment by oxone-999** [comment]
@arncv please assign it to me

**Comment by arncv** [comment]
Assigned!

**Comment by oxone-999** [comment]
after clicking copy link button , which link should get copied

**Comment by arncv** [comment]
The link should redirect to the pop up info page.

If the link is getting errors, you can redirect to the resources page instead.

**Comment by oxone-999** [comment]
Ok
