### ISSUE TITLE
Create a Volunteer Sign-up form

### ISSUE THREAD

**Issue by arncv** [arncv/Intima#36]
**Is your feature request related to a problem? Please describe.**
Currently, there is no streamlined way for users to express their interest in volunteering for our platform. This can lead to missed opportunities and potential volunteers may feel discouraged if the process is not clear and straightforward.

**Describe the solution you'd like**
We would like to implement a volunteer sign-up form on our website. This form would allow users to provide their contact information, areas of interest, availability, and any other relevant information.

The form should include the following fields:

Full Name
Email Address
Phone Number
Areas of Interest (with a dropdown list of options)
Availability (with options for different days and times)
Previous Volunteering Experience (a text box for users to provide details)
Why they are interested in volunteering (a text box for users to express their motivation)
Once the form is submitted, the information should be sent to our volunteer coordination team for review and follow-up at [arnvgl@duck.com](mailto:arnvgl@duck.com).

**Comment by oxone-999** [comment]
@arncv please assign it to me

**Comment by arncv** [comment]
@oxone-999 Assigned !

**Comment by FavourtheDeveloper** [comment]
Is this still open?
I would love to work on it

**Comment by arncv** [comment]
Assigned @FavourtheDeveloper

**Comment by FavourtheDeveloper** [comment]
Hy @arncv , I'm having a problem pushing.
Pls grant me push access

**Comment by FavourtheDeveloper** [comment]
![git capture](https://github.com/arncv/Intima/assets/108767655/f0e13d6a-22b9-428f-bccf-e1f93f26c6bf)

**Comment by arncv** [comment]
Hey @FavourtheDeveloper , could you fork the project first and then open a pull request to merge the changes? That would be convenient while contributing.

**Comment by HarikaB11** [comment]
@arncv , I would like to work on this issue.

**Comment by arncv** [comment]
@HarikaB11 Assigned! The volunteer form needs some changes in the form with some backend too. Let me know if you face any issue.
