### ISSUE TITLE
There is a padding error in the mobile view 

### ISSUE THREAD

**Issue by Codebox124** [arncv/Intima#40]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
![www intima tv_index html(iPhone XR)](https://github.com/arncv/Intima/assets/105174934/b19aa1bc-f4c2-4b75-a3bf-e031163829ac)

**Additional context**

**Comment by arncv** [comment]
Thank you pointing out the bug, Assigned!

**Comment by Codebox124** [comment]
done thanks
