### ISSUE TITLE
Forum page doesn't support dark mode

### ISSUE THREAD

**Issue by yr1404** [arncv/Intima#47]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/arncv/Intima/assets/106465753/effe9db0-f6f2-4dd7-8984-27e5b0706e53)
When switch to dark mode on home page, it automatically gets to light mode in _forum_ page.

**Describe the solution you'd like**
I can add a similar button on the forum page for changing between dark and light modes.

**Describe alternatives you've considered**
The state from the home page can be kept when switching to the forum page.

**Additional context**
NA

**Comment by arncv** [comment]
Assigned!

**Comment by yr1404** [comment]
BTW, I really liked your initiative towards sex edi\ucation in India by creating this website.

**Comment by arncv** [comment]
Thank you❤️

**Comment by TheShiveshNetwork** [comment]
Can you assign this to me too?
