### ISSUE TITLE
[Feat.] Request to Increase the Width of the "Write Your Question" Textarea on the Forum Page

### ISSUE THREAD

**Issue by imSyntn** [arncv/Intima#55]
**Is your feature request related to a problem? Please describe.**
On the forum page, the "Write Your Question" Textarea has a relatively small width, which affects the user experience and does not look aesthetically pleasing. I kindly request that we consider increasing the width of this Textarea to improve usability and visual appeal.

**Describe the solution you'd like**
I suggest that we enhance the "Write Your Question" Textarea by increasing its width. This will allow users to see more of their question content at once, reducing the need for unnecessary line breaks and improving the overall writing experience.

**Additional context**
Screenshot:

![Screenshot 2023-10-07 123045](https://github.com/arncv/Intima/assets/134107725/c6ff406b-88e2-49a1-a8b3-97d34d3a6ac3)

**Comment by arncv** [comment]
Thank for pointing out this bug. This issue is open for contribution

**Comment by shalomrionafernandes** [comment]
@arncv I would like to work on this bug

**Comment by arncv** [comment]
@shalomrionafernandes Assigned!
