### ISSUE TITLE
Make a dropdown menu for language selection

### ISSUE THREAD

**Issue by arncv** [arncv/Intima#69]
![image](https://github.com/arncv/Intima/assets/62099328/081d5f43-5b6d-4cb0-a543-7b7e26df24ff)

Currently the menu for language selection takes up too much space.
**Proposed Changes**

- Make a dropdown menu for selecting language. Default should be English.

**Comment by sotiriszogos** [comment]
Hello, could you please assign it to me?

**Comment by arncv** [comment]
Assigned!
