### ISSUE TITLE
Dark Mode Implementation

### ISSUE THREAD

**Issue by arncv** [arncv/Intima#7]
Enhance user comfort and experience by offering a dark theme, reducing eye strain during extended use.

**Comment by hemanth110702** [comment]
Hey, I would like to work on this. Can you please assign this to me?

**Comment by arncv** [comment]
Assigned!

**Comment by Chitresh-code** [comment]
Is this issue still available? I would like to work on it.

**Comment by arncv** [comment]
@Chitresh-code Yeah the issue is still available. Assigned to you too!

**Comment by Chitresh-code** [comment]
Check your pull requests.

**Comment by hemanth110702** [comment]
Can you please check the pull request. I have done the changes.
