### ISSUE TITLE
Add more resources in the Resources Section

### ISSUE THREAD

**Issue by arncv** [arncv/Intima#71]
![image](https://github.com/arncv/Intima/assets/62099328/7ed4bae9-1966-4deb-9530-2f3c0b4b9e2a)

There are blank spaces currently in the resources section. Add 2 resources in those on different topic from others. 
The resources should include
- Description
- Link to learn more  about the topic

**Comment by ayu5hagarwal** [comment]
i can do it, @arncv   can you assign it to me.

**Comment by arncv** [comment]
@ayu5hagarwal Assigned!

**Comment by belkhoujaons** [comment]
I could help in that, can u assign it to me ?

**Comment by arncv** [comment]
@belkhoujaons Assigned it to you too!
