### ISSUE TITLE
Add a Next Button in Quiz.

### ISSUE THREAD

**Issue by arncv** [arncv/Intima#72]
![image](https://github.com/arncv/Intima/assets/62099328/e4a39a6d-e2cb-4f26-9aea-8e2d7dc9cdc9)
The quiz section has only 1 button "SUBMIT" to go to both next question and submit the quiz.
Proposed Changes
![image](https://github.com/arncv/Intima/assets/62099328/ae133db8-de0b-4764-8dd5-ef956996313e)
Make a new button Next to go to the next question till their is no question left and at the end question ,Submit button should be used to submit the quiz.

**Comment by PatrikTimko** [comment]
Hello, can you assign to this?

**Comment by arncv** [comment]
Assigned!

**Comment by aatiw** [comment]
can you assign me this issue?

**Comment by arncv** [comment]
Assigned!
