### ISSUE TITLE
Improve Quiz Page UI

### ISSUE THREAD

**Issue by arncv** [arncv/Intima#73]
# Current
The Quiz page currently  is very different from the main page with no navigation bar, no main page button.

![image](https://github.com/arncv/Intima/assets/62099328/d3566738-d2b2-4fee-ada5-8098121c16c1)
# **Proposed Changes:**

Add a navigation bar at the top of the quiz & Improve the overall UI.

![image](https://github.com/arncv/Intima/assets/62099328/5e0fc26d-df2e-4d2f-b77f-b201c02d62d7)

**Comment by kenyipaul** [comment]
Assign me to this

**Comment by arncv** [comment]
Assigned!

**Comment by aatiw** [comment]
please assign me this issue
