### ISSUE TITLE
The form is executed with blank fields.

### ISSUE THREAD

**Issue by ivanosquis10** [arncv/Intima#77]
The form input at the bottom of the main page, where it says "volunteer", executes the function with blank fields.

I propose to create the function "submit", with the validation and avoid the default behavior :)

Nice project btw, good luck <3

**Comment by Basavarajakjbasuu** [comment]
I will contribute on this could you please assig to me

**Comment by arncv** [comment]
@ivanosquis10 Thank you ❤️
@Basavarajakjbasuu Assigned it to you! :)
