### ISSUE TITLE
Improve Readme & Add Documentations

### ISSUE THREAD

**Issue by arncv** [arncv/Intima#9]
The current README provides a good overview of the Intima platform. However, to ensure clarity, ease of use, and to provide comprehensive information to both users and contributors, we need to enhance and expand the README documentation.

Additionally, we aim to include a Code of Conduct and Contributing Guidelines to create a friendly and inclusive environment for everyone involved.

**Comment by Yasir761** [comment]
Can your assign it to me?

**Comment by arncv** [comment]
Assigned! :)

**Comment by Yasir761** [comment]
@arncv , while I was going through Readme file, tbh it does not need any more enhancement but we can make a separate file for Contributing and code of conduct like CODE_OF_CONDUCT.md and Contributing.md respectively.

**Comment by Yasir761** [comment]
@arncv Sure, I will merge them into one and provide link in readme file, Thank You.
