### ISSUE TITLE
Language Change Button not working

### ISSUE THREAD

**Issue by arncv** [arncv/Intima#90]
The language button is broken. Clicking it should toggle the language on the page, but instead it does nothing. 
![image](https://github.com/arncv/Intima/assets/62099328/a1c849c6-7e5b-4994-866f-66df007f1eb7)

**Comment by mridulabatra** [comment]
please assign me this issue under Hacktoberfest 2023

**Comment by arncv** [comment]
Assigned!

**Comment by arncv** [comment]
Looks like this was fixed in the latest PR, closing the issue.
